# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'
- task: HelmDeploy@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 'azuedevops-kube'
    namespace: 'default'
    command: 'install'
    chartType: 'FilePath'
    chartPath: 'helm-chart/fasilchart'
    chartVersion: '$(Build.BuildId)'