# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: default 

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      helm upgrade --install hello-java ./helm-chart/fasilchart\
            --namespace default \
            --set image.tag=$(IMAGE_TAG)